import lantern_l from '../assets/anim/lantern-l.mp4';
import lantern_p from '../assets/anim/lantern-p.mp4';
import neon_l from '../assets/anim/neon-l.mp4';
import neon_p from '../assets/anim/neon-p.mp4';
import tram_l from '../assets/anim/tram-l.mp4';
import tram_p from '../assets/anim/tram-p.mp4';
import mahjong_l from '../assets/anim/mahjong-l.mp4';
import mahjong_p from '../assets/anim/mahjong-p.mp4';
import coins_l from '../assets/anim/coins-l.mp4';
import coins_p from '../assets/anim/coins-p.mp4';
import lion_l from '../assets/anim/lion-l.mp4';
import lion_p from '../assets/anim/lion-p.mp4';
import envelope_l from '../assets/anim/envelope-l.mp4';
import envelope_p from '../assets/anim/envelope-p.mp4';
import tram_tail_l from '../assets/anim/tram-tail-l.mp4';
import tram_tail_p from '../assets/anim/tram-tail-p.mp4';
import coins_tail_l from '../assets/anim/coins-tail-l.mp4';
import coins_tail_p from '../assets/anim/coins-tail-p.mp4';
import mahjong_tail_l from '../assets/anim/mahjong-tail-l.mp4';
import mahjong_tail_p from '../assets/anim/mahjong-tail-p.mp4';

/**
 * One shot per clip, generated by Higgsfield at native 1080p in BOTH
 * orientations (1920x1080 for desktop, 1080x1920 for phones) so neither is
 * stretched, then trimmed/sped up with ffmpeg to ~1.9s and encoded H.264.
 * Shots are screen-blended over the page, so black is transparent; no alpha
 * channel is needed.
 *
 * peakMs is the moment (in the trimmed clip) when the picture covers the
 * screen — the route swaps there, so the page change is hidden behind it.
 * Several clips do not clear to black by themselves, so RouteFx also fades
 * the picture out over its last stretch.
 */
export interface ClipVariant {
  id: string;
  src: string;
  durationMs: number;
  peakMs: number;
}

export interface Clip {
  land: ClipVariant;
  port: ClipVariant;
}

export type Orientation = 'land' | 'port';

export function currentOrientation(): Orientation {
  return typeof window !== 'undefined' &&
    window.matchMedia('(orientation: portrait)').matches
    ? 'port'
    : 'land';
}

export const CLIPS = {
  lantern: {
    land: { id: 'lantern-l', src: lantern_l, durationMs: 1950, peakMs: 950 },
    port: { id: 'lantern-p', src: lantern_p, durationMs: 1882, peakMs: 1294 },
  },
  neon: {
    land: { id: 'neon-l', src: neon_l, durationMs: 1850, peakMs: 1050 },
    port: { id: 'neon-p', src: neon_p, durationMs: 1886, peakMs: 1029 },
  },
  tram: {
    land: { id: 'tram-l', src: tram_l, durationMs: 1900, peakMs: 750 },
    port: { id: 'tram-p', src: tram_p, durationMs: 1897, peakMs: 974 },
  },
  mahjong: {
    land: { id: 'mahjong-l', src: mahjong_l, durationMs: 1895, peakMs: 842 },
    port: { id: 'mahjong-p', src: mahjong_p, durationMs: 1875, peakMs: 1437 },
  },
  coins: {
    land: { id: 'coins-l', src: coins_l, durationMs: 1950, peakMs: 850 },
    port: { id: 'coins-p', src: coins_p, durationMs: 1895, peakMs: 632 },
  },
  lion: {
    land: { id: 'lion-l', src: lion_l, durationMs: 1950, peakMs: 600 },
    port: { id: 'lion-p', src: lion_p, durationMs: 1882, peakMs: 1000 },
  },
  envelope: {
    land: { id: 'envelope-l', src: envelope_l, durationMs: 1900, peakMs: 850 },
    port: { id: 'envelope-p', src: envelope_p, durationMs: 1882, peakMs: 1176 },
  },
  tramTail: {
    land: { id: 'tram-tail-l', src: tram_tail_l, durationMs: 650, peakMs: 0 },
    port: { id: 'tram-tail-p', src: tram_tail_p, durationMs: 650, peakMs: 0 },
  },
  coinsTail: {
    land: { id: 'coins-tail-l', src: coins_tail_l, durationMs: 650, peakMs: 0 },
    port: { id: 'coins-tail-p', src: coins_tail_p, durationMs: 650, peakMs: 0 },
  },
  mahjongTail: {
    land: { id: 'mahjong-tail-l', src: mahjong_tail_l, durationMs: 650, peakMs: 0 },
    port: { id: 'mahjong-tail-p', src: mahjong_tail_p, durationMs: 650, peakMs: 0 },
  },
} satisfies Record<string, Clip>;

/**
 * cover:  play the whole shot, swap the route at the peak (the screen is
 *         fully covered), then reveal. The new page appears ~1s late.
 * reveal: swap the route at once and play only the *Tail clip (the picture
 *         clearing away) over the new page, never blocking taps. Used on the
 *         buy path (register -> queue -> order), where a second of added
 *         delay costs real seats.
 */
export type Mode = 'cover' | 'reveal';

export interface Plan {
  clip: ClipVariant;
  mode: Mode;
}

/** One storyboard shot per part of the site. null = no transition at all. */
export function planFor(pathname: string, o: Orientation): Plan | null {
  // Door staff, a guest opening a shared ticket, and the back office must
  // never wait on an animation.
  if (
    pathname.startsWith('/admin') ||
    pathname.startsWith('/checkin') ||
    pathname.startsWith('/t/') ||
    pathname.startsWith('/lab-3d')
  ) {
    return null;
  }
  if (pathname === '/' || pathname === '/events') return { clip: CLIPS.lantern[o], mode: 'cover' };
  if (pathname.startsWith('/events/')) return { clip: CLIPS.neon[o], mode: 'cover' };
  if (pathname === '/login' || pathname === '/profile') return { clip: CLIPS.envelope[o], mode: 'cover' };
  if (pathname.startsWith('/register/')) return { clip: CLIPS.mahjongTail[o], mode: 'reveal' };
  if (pathname.startsWith('/queue/')) return { clip: CLIPS.tramTail[o], mode: 'reveal' };
  if (pathname.startsWith('/order/') || pathname.startsWith('/orders/')) {
    return { clip: CLIPS.coinsTail[o], mode: 'reveal' };
  }
  if (pathname === '/my-tickets' || pathname === '/entry-guide') {
    return { clip: CLIPS.mahjong[o], mode: 'cover' };
  }
  if (pathname === '/trailer') return { clip: CLIPS.lion[o], mode: 'cover' };
  return null;
}
